local window = require("examples.createwindow")

function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("@render:", "use_fixed_fit_projection", { near = -1, far = 1 })
end

function on_input(self, action_id, action)
	if action_id == hash("key_1") and action.pressed then
		require("examples.messagebox")
	end
	if action_id == hash("key_2") and action.pressed then
		window.makeWindow()
	end
end
